version: '3.0'

services:
  server:
    container_name: server
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: yarn start:dev
    depends_on:
      - mongo
    restart: always
