name: Dev-CI

on:
  push:
    branches: [ dev, master ]

jobs:
  install: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     
     - name: Install packages
       run: npm i
      
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run build
        run: npm run build
  staging-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Heroku deploy
        if: github.ref == 'refs/heads/dev'
        run: dpl --provider=heroku --app=${{ secrets.HEROKU_APP_STAGING }} --api-key=${{ secrets.HEROKU_API_KEY }}
        
    
